# Generated by Django 5.1.4 on 2024-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20241217_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
