# Generated by Django 5.1.4 on 2025-03-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_restaurantreview_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together={('reviewer_name', 'restaurant')},
        ),
    ]
