# Generated by Django 5.1.4 on 2025-03-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_restaurantreview_options_menureview'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menureview',
            index=models.Index(fields=['menu'], name='main_app_menu_review_menu_id'),
        ),
    ]
