# Generated by Django 5.0.4 on 2024-12-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_exercise_calories_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=90),
        ),
    ]
