# Generated by Django 5.1.4 on 2025-03-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_felbladedemonhunter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viperassassin',
            old_name='venomous_strike_mastery',
            new_name='venomous_strikes_mastery',
        ),
    ]
