# Generated by Django 5.1.4 on 2025-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userprofile_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
