# Generated by Django 5.1.4 on 2025-03-09 13:21

import main_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=main_app.models.StudentIDField(),
        ),
    ]
