# Generated by Django 5.1.4 on 2025-01-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_lecturerprofile_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.lecturer'),
        ),
    ]
